### PR TITLE
Postgres: support for `OWNER TO` clause

### LINKED ISSUE #1293: Please support "alter table owner to" in Postgres
## Version

sqlparser = "0.46.0"

## 

https://www.postgresql.org/docs/16/sql-altertable.html

```rust
use sqlparser::dialect::PostgreSqlDialect;
use sqlparser::parser::Parser;

fn main() {

    let sql = "-- auto-generated definition
    alter table my_table owner to my_user";

    let dialect = PostgreSqlDialect {}; // or AnsiDialect, or your own dialect ...

    let ast = Parser::parse_sql(&dialect, sql).unwrap();

    println!("AST: {:?}", ast);
}
```

```
thread 'main' panicked at src/main.rs:11:48:
called `Result::unwrap()` on an `Err` value: ParserError("Expected ADD, RENAME, PARTITION, SWAP, DROP, or SET TBLPROPERTIES after ALTER TABLE, found: owner at Line: 2, Column 26")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: sqlreviewer::main
             at ./src/main.rs:11:15
   5: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101

```

### PR DESCRIPTION
**Pull request by gainings**
Support `OWNER TO` clause just for Postgres dialect
Closes #1293

### CODE REVIEW

File: src/ast/ddl.rs [hunk 1]
```diff
@@ -157,6 +157,28 @@ pub enum AlterTableOperation {
     SwapWith { table_name: ObjectName },
     /// 'SET TBLPROPERTIES ( { property_key [ = ] property_val } [, ...] )'
     SetTblProperties { table_properties: Vec<SqlOption> },
+
+    /// `OWNER TO { <new_owner> | CURRENT_ROLE | CURRENT_USER | SESSION_USER }`
+    ///
+    /// Note: this is a PostgreSQL-specific operation.
```
Comment (iffyio) [inline src/ast/ddl.rs:163]: Could we include a link to the docs for the feature? I think it'd be this one https://www.postgresql.org/docs/current/sql-altertable.html

File: src/ast/ddl.rs [hunk 2]
```diff
@@ -157,6 +157,28 @@ pub enum AlterTableOperation {
...
+    OwnerTo { new_owner: Owner },
+}
+
+#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
+#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
+#[cfg_attr(feature = "visitor", derive(Visit, VisitMut))]
+pub enum Owner {
+    Ident(Ident),
+    Expr(Expr),
+}
```
Comment (iffyio) [inline src/ast/ddl.rs:173]:
```suggestion
pub enum Owner {
    Ident(Ident),
    CurrentRole,
    CurrentUser
    SessionUser
}
```
I'm thinking the Expr might be somewhat opaque to represent the others, from the docs the other variants seem enumerable so figured we can represent them verbatim in the enum as above?

File: src/parser/mod.rs [hunk 3]
```diff
@@ -6274,6 +6274,30 @@ impl<'a> Parser<'a> {
             self.expect_keyword(Keyword::WITH)?;
             let table_name = self.parse_object_name(false)?;
             AlterTableOperation::SwapWith { table_name }
+        } else if dialect_of!(self is PostgreSqlDialect)
```
Comment (iffyio) [inline src/parser/mod.rs:6277]:
```suggestion
        } else if dialect_of!(self is PostgreSqlDialect | GenericDialect)
```
if no conflicts we can include support for the generic dialect

File: src/parser/mod.rs [hunk 4]
```diff
@@ -6274,6 +6274,30 @@ impl<'a> Parser<'a> {
...
+            && self.parse_keywords(&[Keyword::OWNER, Keyword::TO])
+        {
+            let next_token = self.next_token();
+            let new_owner = match next_token.token {
+                Token::DoubleQuotedString(ref s) => Owner::Ident(Ident::new(s.to_string())),
```
Comment (iffyio) [inline src/parser/mod.rs:6282]: instead of having two separate cases (this DoubleQuotedString and NoKeyword below) to handle the ident variant, would it make sense to call `parse_identifier` if none of the other variants match?
so roughly
```rust
match self.parse_one_of_keywords(&[CURRENT_USER, CURRENT_ROLE, SESSION_USER]) {
    Some(CURRENT_USER) => {}
    ...
    _ =|> self.parse_identifier()
}
```

File: src/ast/ddl.rs (hunk 2 above)
Comment (gainings) [reply src/ast/ddl.rs:173]: @iffyio Thanks for the review!

Currently `CURRENT_USER`, and `SESSION_USER` are supported as Expr::Function like this.

```
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] Parsing sql 'SELECT CURRENT_USER, CURRENT_ROLE, SESSION_USER;
'...
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] parsing expr
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] prefix: Function(Function { name: ObjectName([Ident { value: "CURRENT_USER", quote_style: None }]), args: None, filter: None, null_treatment: None, over: None, within_group: [] })
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] get_next_precedence() TokenWithLocation { token: Comma, location: Location { line: 1, column: 20 } }
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] 0: , 1: CURRENT_ROLE 2: ,
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] next precedence: 0
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] parsing expr
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] prefix: Identifier(Ident { value: "CURRENT_ROLE", quote_style: None })
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] get_next_precedence() TokenWithLocation { token: Comma, location: Location { line: 1, column: 34 } }
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] 0: , 1: SESSION_USER 2: ;
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] next precedence: 0
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] parsing expr
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] prefix: Function(Function { name: ObjectName([Ident { value: "SESSION_USER", quote_style: None }]), args: None, filter: None, null_treatment: None, over: None, within_group: [] })
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] get_next_precedence() TokenWithLocation { token: SemiColon, location: Location { line: 1, column: 48 } }
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] 0: ; 1: EOF 2: EOF
2024-06-22T13:04:10.639Z DEBUG [sqlparser::parser] next precedence: 0
```
https://github.com/sqlparser-rs/sqlparser-rs/blob/f16c1afed0fa273228e74a633f3885c9c6609911/src/parser/mod.rs#L998-L1010

I think it would be better to maintain this compatibility.

Additionally, `CURRENT_ROLE` must also be considered.

Comment (iffyio) [reply src/ast/ddl.rs:173]: Ah I see, I think it makes a lot of sense to represent them as functions when parsing arbitrary expressions - when parsing an `Owner` however, spontaneously doesn't feel the same since the context is much more restricted. Thinking here we can be explicit about what comes out of the parser which would be desirable from an API pov.

File: src/parser/mod.rs (hunk 4 above)
Comment (alamb) [reply src/parser/mod.rs]: in 0ff17d7

File: src/parser/mod.rs (hunk 3 above)
Comment (alamb) [reply src/parser/mod.rs]: Done in 25d6a40

File: src/ast/ddl.rs (hunk 2 above)
Comment (alamb) [reply src/ast/ddl.rs]: I agree it is better to be explicit and match the allowed postgres syntax more exactly. I double checked https://www.postgresql.org/docs/current/sql-altertable.html and it says:

>     OWNER TO { new_owner | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
>
> ...
> new_owner 
>   The user name of the new owner of the table.


So I think @iffyio 's suggestion is a good one.

I took the liberty of making this change in 0ff17d7 as I am preparing for a sqlparser release

File: src/parser/mod.rs [hunk 5]
```diff
@@ -6425,6 +6425,25 @@ impl<'a> Parser<'a> {
...
+            let new_owner = match self.parse_one_of_keywords( &[Keyword::CURRENT_USER, Keyword::CURRENT_ROLE, Keyword::SESSION_USER]) {
+                Some(Keyword::CURRENT_USER) => Owner::CurrentUser,
+                Some(Keyword::CURRENT_ROLE) => Owner::CurrentRole,
+                Some(Keyword::SESSION_USER) => Owner::SessionUser,
+                Some(_) => unreachable!(),
+                None => {
+                    match self.parse_identifier(false) {
+                        Ok(ident) => Owner::Ident(ident),
+                        Err(e) => {
+                            return Err(ParserError::ParserError(format!("Expected CURRENT_USER, CURRENT_ROLE, SESSION_USER or identifier after OWNER TO. {e}")))
```
Comment (alamb) [inline src/parser/mod.rs:6440]: Making sure the error message had some additional context was the only thing that I found awkward. Otherwise I think @iffyio 's suggestions made the code easier to understand and easier to use overall

**Review by alamb — APPROVED** [review]
@gainings  and @iffyio if you have a moment to review the changes I made to this PR I would be most appreciative. I am hoping to get a sqlparser-rs release out tomorrow: https://github.com/sqlparser-rs/sqlparser-rs/issues/1296

**Review by iffyio — APPROVED** [review]
Changes LGTM!

**Comment by alamb** [comment]
Thanks again @gainings and @iffyio

**Comment by gainings** [comment]
Thank you for @alamb and @iffyio 
And I apologize for the delayed response.

**Comment by alamb** [comment]
No worries -- thank you for the contribution @gainings  and I apologize for my late review / update.
