### PR TITLE
Fix Hive table comment should be after table column definitions

### LINKED ISSUE #1395: HiveDialect doesn't support create table with PARTITIONED BY and CLUSTERED BY clause
When I used the Hive dialect to parse the following Hive SQL, I encountered the following error.
```
    CREATE TABLE user_info_bucketed(user_id BIGINT, firstname STRING, lastname STRING)
    COMMENT 'A bucketed copy of user_info'
    PARTITIONED BY(ds STRING)
    CLUSTERED BY(user_id) INTO 256 BUCKETS;
```
with error
```
Err(ParserError("Expected: end of statement, found: PARTITIONED at Line: 4, Column: 5"))
```
Here is the code I tested.
```rust
use sqlparser::dialect::HiveDialect;
use sqlparser::parser::Parser;

fn main() {
    let query = r#"
    CREATE TABLE user_info_bucketed(user_id BIGINT, firstname STRING, lastname STRING)
    COMMENT 'A bucketed copy of user_info'
    PARTITIONED BY(ds STRING)
    CLUSTERED BY(user_id) INTO 256 BUCKETS;"#;
    let dialect = HiveDialect {};
    let ast = Parser::parse_sql(&dialect, query);
    println!("ast={:?}", ast);
}
```

image

### PR DESCRIPTION
**Pull request by git-hulk**
For the documentation, please refer to:
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateTable

This closes #1395

### CODE REVIEW

**Comment by git-hulk** [comment]
cc @iffyio

File: src/parser/mod.rs [hunk 1]
```diff
@@ -5723,16 +5734,19 @@ impl<'a> Parser<'a> {
...
-            let next_token = self.next_token();
-            match next_token.token {
-                Token::SingleQuotedString(str) => Some(CommentDef::WithoutEq(str)),
-                _ => self.expected("comment", next_token)?,
-            }
-        } else {
-            None
-        };
+        // For Hive, the comment is after the table column definitions
+        if !dialect_of!(self is HiveDialect) {
```
Comment (iffyio) [inline src/parser/mod.rs:5738]: is this correct to switch this to being guarded on the Hive dialect (other dialects didn't support it previously)?

File: src/parser/mod.rs [hunk 2]
```diff
@@ -5723,16 +5734,19 @@ impl<'a> Parser<'a> {
...
+            comment = if self.parse_keyword(Keyword::COMMENT) {
+                let _ = self.consume_token(&Token::Eq);
+                let next_token = self.next_token();
+                match next_token.token {
+                    Token::SingleQuotedString(str) => Some(CommentDef::WithoutEq(str)),
```
Comment (iffyio) [inline src/parser/mod.rs:5743]: > For Hive, the comment is after the table column definitions

Not sure I followed this part, the comment seems to suggest this should also use `CommentDef::AfterColumnDefsWithoutEq`?

File: src/parser/mod.rs (hunk 1 above)
Comment (git-hulk) [reply src/parser/mod.rs:5738]: I see, the comment line is a bit misleading. I use `!dialect_of!(self is HiveDialect)` here to disallow `Hive` to parse the comment here?

File: src/parser/mod.rs (hunk 2 above)
Comment (git-hulk) [reply src/parser/mod.rs:5743]: It should be correct to use `CommentDef::WithoutEq` since it will parse comment line for other dialects except here.

File: src/parser/mod.rs [hunk 3]
```diff
@@ -5723,16 +5734,19 @@ impl<'a> Parser<'a> {
...
-            let _ = self.consume_token(&Token::Eq);
-            let next_token = self.next_token();
-            match next_token.token {
-                Token::SingleQuotedString(str) => Some(CommentDef::WithoutEq(str)),
-                _ => self.expected("comment", next_token)?,
-            }
-        } else {
-            None
-        };
+        // For Hive, the comment is after the table column definitions
```
Comment (git-hulk) [inline src/parser/mod.rs:5737]:
```suggestion
        // Excludes Hive dialect here since it has been handled after table column definitions.
```

File: src/parser/mod.rs [hunk 4]
```diff
@@ -5723,16 +5734,19 @@ impl<'a> Parser<'a> {
...
-            match next_token.token {
-                Token::SingleQuotedString(str) => Some(CommentDef::WithoutEq(str)),
-                _ => self.expected("comment", next_token)?,
-            }
-        } else {
-            None
-        };
+        // Excludes Hive dialect here since it has been handled after table column definitions.
+        if !dialect_of!(self is HiveDialect) {
+            comment = if self.parse_keyword(Keyword::COMMENT) {
```
Comment (iffyio) [inline src/parser/mod.rs:5739]: we can probably merge this with the dialect check to be `if !dialect_of() && self.parse_keyword()`? I think that lets us skip the `else { None }` block

File: src/parser/mod.rs (hunk 1 above)
Comment (iffyio) [reply src/parser/mod.rs:5738]: Oh right! 😅 my bad seems I'm used to seeing if dialect_of and my brain skipped the !

File: src/parser/mod.rs (hunk 2 above)
Comment (iffyio) [reply src/parser/mod.rs:5743]: Yeah that sounds good! this was due to my misreading the dialect check

**Review by iffyio — APPROVED** [review]
LGTM! cc @alamb

File: src/parser/mod.rs (hunk 4 above)
Comment (git-hulk) [reply src/parser/mod.rs]: Good point, has been changed according to the suggestion.

**Review by alamb — APPROVED** [review]
Thanks @git-hulk and @iffyio
