### PR TITLE
Fix "BEGIN TRANSACTION" being serialized as "START TRANSACTION"

### LINKED ISSUE #919: "BEGIN TRANSACTION" gets stringified as "START TRANSACTION"
Parsing the following:

```sql
BEGIN;
```

and then calling `.to_string()` on the parsed statement, results in 

```sql
START TRANSACTION;
```

The `START` syntax in not supported in SQLite. But ideally, the parser would keep track of which variant of the syntax was used, and be able to use it in the `Format` implementation.

### PR DESCRIPTION
**Pull request by lovasoa**
"START TRANSACTION" is not valid in SQLite, which means that valid
SQLite SQL code, when parsed and re-serialized by sqlparser, would become invalid.

Fixes #919

### CODE REVIEW

**Comment by lovasoa** [comment]
@alamb , is that okay for you? I need this for SQLPage.

**Comment by parkma99** [comment]
LGTM @lovasoa Thanks

File: src/ast/mod.rs [hunk 1]
```diff
@@ -1541,7 +1541,10 @@ pub enum Statement {
     /// Note: This is a MySQL-specific statement.
     Use { db_name: Ident },
     /// `{ BEGIN [ TRANSACTION | WORK ] | START TRANSACTION } ...`
-    StartTransaction { modes: Vec<TransactionMode> },
+    StartTransaction {
+        modes: Vec<TransactionMode>,
+        syntax_begin: bool,
```
Comment (alamb) [inline src/ast/mod.rs:1546]: Could we perhaps add a comment explaining what `syntax_begin` means (so that people don't have to look at the source code?)

Maybe 
```
    /// `START  [ TRANSACTION | WORK ] | START TRANSACTION } ...`
    /// If `syntax_begin` is false.
    ///
    /// `BEGIN  [ TRANSACTION | WORK ] | START TRANSACTION } ...`
    /// If `syntax_begin` is true
````

?

Comment (alamb) [reply src/ast/mod.rs:1546]: Also, calling this field `begin` might be more consistent with the rest of this crate but `syntax_begin` is fine as well

**Review by alamb — APPROVED** [review]
Looks good to me @lovasoa  -- thank you.

I had one request re documentation and a naming suggestion  but otherwise  this looks great

**Comment by lovasoa** [comment]
thanks @alamb . I implemented your suggestions.

**Comment by alamb** [comment]
Thanks @lovasoa
