### PR TITLE
Distinguish between `SELECT * FROM foo` and `SELECT * FROM foo()`

### LINKED ISSUE #405: Cannot distinguish between `SELECT * FROM foo` and `SELECT * FROM foo()`
`sqlparser::ast::TableFactor::Table` just represents the arguments as a `Vec<FunctionArg>` both
`SELECT * FROM foo` and `SELECT * FROM foo()` and are parsed as:

```
Table { name: ObjectName([Ident { value: "foo", quote_style: None }]), alias: None, args: [], with_hints: [] }
```

This is apparently a regression that was introduced in 5652b4676c65f0875fd8c4849dd7cb27c819bef6 (#73).

### PR DESCRIPTION
**Pull request by razzolini-qpq**
Fixes #405. As stated in that issue,

> This is apparently a regression that was introduced in https://github.com/sqlparser-rs/sqlparser-rs/commit/5652b4676c65f0875fd8c4849dd7cb27c819bef6 (https://github.com/sqlparser-rs/sqlparser-rs/pull/73)

To fix it, I reintroduced the `Option` around the vector of arguments, which was removed in 5652b4676c65f0875fd8c4849dd7cb27c819bef6 even though it wasn't actually redundant. I also added a test which ensures that `SELECT * FROM fn()` is not modified after a serialization round-trip, and I added a brief explanation of the different meanings of `None` and `Some` (including `Some(vec![])`) to the documentation.

### CODE REVIEW

File: src/ast/query.rs [hunk 1]
```diff
@@ -337,7 +337,11 @@ pub enum TableFactor {
         /// Arguments of a table-valued function, as supported by Postgres
         /// and MSSQL. Note that deprecated MSSQL `FROM foo (NOLOCK)` syntax
         /// will also be parsed as `args`.
-        args: Vec<FunctionArg>,
+        ///
+        /// This field's value is `Some(v)`, where `v` is a (possibly empty)
```
Comment (alamb) [inline src/ast/query.rs:341]: 👍

**Review by alamb — APPROVED** [review]
LGTM -- thank you @razzolini-qpq
